require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserPotentialsController do

  # This should return the minimal set of attributes required to create a valid
  # UserPotential. As you add validations to UserPotential, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserPotentialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all user_potentials as @user_potentials" do
      user_potential = UserPotential.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:user_potentials)).to eq([user_potential])
    end
  end

  describe "GET show" do
    it "assigns the requested user_potential as @user_potential" do
      user_potential = UserPotential.create! valid_attributes
      get :show, {:id => user_potential.to_param}, valid_session
      expect(assigns(:user_potential)).to eq(user_potential)
    end
  end

  describe "GET new" do
    it "assigns a new user_potential as @user_potential" do
      get :new, {}, valid_session
      expect(assigns(:user_potential)).to be_a_new(UserPotential)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_potential as @user_potential" do
      user_potential = UserPotential.create! valid_attributes
      get :edit, {:id => user_potential.to_param}, valid_session
      expect(assigns(:user_potential)).to eq(user_potential)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserPotential" do
        expect {
          post :create, {:user_potential => valid_attributes}, valid_session
        }.to change(UserPotential, :count).by(1)
      end

      it "assigns a newly created user_potential as @user_potential" do
        post :create, {:user_potential => valid_attributes}, valid_session
        expect(assigns(:user_potential)).to be_a(UserPotential)
        expect(assigns(:user_potential)).to be_persisted
      end

      it "redirects to the created user_potential" do
        post :create, {:user_potential => valid_attributes}, valid_session
        expect(response).to redirect_to(UserPotential.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_potential as @user_potential" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserPotential.any_instance.stub(:save).and_return(false)
        post :create, {:user_potential => { "email" => "invalid value" }}, valid_session
        expect(assigns(:user_potential)).to be_a_new(UserPotential)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserPotential.any_instance.stub(:save).and_return(false)
        post :create, {:user_potential => { "email" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_potential" do
        user_potential = UserPotential.create! valid_attributes
        # Assuming there are no other user_potentials in the database, this
        # specifies that the UserPotential created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(UserPotential).to receive(:update).with({ "email" => "MyString" })
        put :update, {:id => user_potential.to_param, :user_potential => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested user_potential as @user_potential" do
        user_potential = UserPotential.create! valid_attributes
        put :update, {:id => user_potential.to_param, :user_potential => valid_attributes}, valid_session
        expect(assigns(:user_potential)).to eq(user_potential)
      end

      it "redirects to the user_potential" do
        user_potential = UserPotential.create! valid_attributes
        put :update, {:id => user_potential.to_param, :user_potential => valid_attributes}, valid_session
        expect(response).to redirect_to(user_potential)
      end
    end

    describe "with invalid params" do
      it "assigns the user_potential as @user_potential" do
        user_potential = UserPotential.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserPotential.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_potential.to_param, :user_potential => { "email" => "invalid value" }}, valid_session
        expect(assigns(:user_potential)).to eq(user_potential)
      end

      it "re-renders the 'edit' template" do
        user_potential = UserPotential.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserPotential.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_potential.to_param, :user_potential => { "email" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_potential" do
      user_potential = UserPotential.create! valid_attributes
      expect {
        delete :destroy, {:id => user_potential.to_param}, valid_session
      }.to change(UserPotential, :count).by(-1)
    end

    it "redirects to the user_potentials list" do
      user_potential = UserPotential.create! valid_attributes
      delete :destroy, {:id => user_potential.to_param}, valid_session
      expect(response).to redirect_to(user_potentials_url)
    end
  end

end
